### ISSUE TITLE
 Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by pritul2** [wonderit/indoor-segmentation-android#5]
I am getting the following the error at run time
`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tensorflow.segmentation/org.tensorflow.demo.SegmentationActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f030000 type #0x1c is not valid
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`

**Comment by wonderit** [comment]
I think it will be solved if you clean and rebuild the project :)
